/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PanelSettingsRouteImport } from './routes/panel/settings'
import { Route as PanelServicesRouteImport } from './routes/panel/services'
import { Route as PanelProfileRouteImport } from './routes/panel/profile'
import { Route as PanelCalendarRouteImport } from './routes/panel/calendar'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelSettingsRoute = PanelSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PanelRoute,
} as any)
const PanelServicesRoute = PanelServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProfileRoute = PanelProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PanelRoute,
} as any)
const PanelCalendarRoute = PanelCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/calendar': typeof PanelCalendarRoute
  '/panel/profile': typeof PanelProfileRoute
  '/panel/services': typeof PanelServicesRoute
  '/panel/settings': typeof PanelSettingsRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/calendar': typeof PanelCalendarRoute
  '/panel/profile': typeof PanelProfileRoute
  '/panel/services': typeof PanelServicesRoute
  '/panel/settings': typeof PanelSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/calendar': typeof PanelCalendarRoute
  '/panel/profile': typeof PanelProfileRoute
  '/panel/services': typeof PanelServicesRoute
  '/panel/settings': typeof PanelSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/panel'
    | '/panel/calendar'
    | '/panel/profile'
    | '/panel/services'
    | '/panel/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/panel'
    | '/panel/calendar'
    | '/panel/profile'
    | '/panel/services'
    | '/panel/settings'
  id:
    | '__root__'
    | '/login'
    | '/panel'
    | '/panel/calendar'
    | '/panel/profile'
    | '/panel/services'
    | '/panel/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/settings': {
      id: '/panel/settings'
      path: '/settings'
      fullPath: '/panel/settings'
      preLoaderRoute: typeof PanelSettingsRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/services': {
      id: '/panel/services'
      path: '/services'
      fullPath: '/panel/services'
      preLoaderRoute: typeof PanelServicesRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/profile': {
      id: '/panel/profile'
      path: '/profile'
      fullPath: '/panel/profile'
      preLoaderRoute: typeof PanelProfileRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/calendar': {
      id: '/panel/calendar'
      path: '/calendar'
      fullPath: '/panel/calendar'
      preLoaderRoute: typeof PanelCalendarRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelCalendarRoute: typeof PanelCalendarRoute
  PanelProfileRoute: typeof PanelProfileRoute
  PanelServicesRoute: typeof PanelServicesRoute
  PanelSettingsRoute: typeof PanelSettingsRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelCalendarRoute: PanelCalendarRoute,
  PanelProfileRoute: PanelProfileRoute,
  PanelServicesRoute: PanelServicesRoute,
  PanelSettingsRoute: PanelSettingsRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
