/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as LogowanieRouteImport } from './routes/logowanie'
import { Route as PanelUstawieniaRouteImport } from './routes/panel/ustawienia'
import { Route as PanelUslugiRouteImport } from './routes/panel/uslugi'
import { Route as PanelProfilRouteImport } from './routes/panel/profil'
import { Route as PanelKalendarzRouteImport } from './routes/panel/kalendarz'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const LogowanieRoute = LogowanieRouteImport.update({
  id: '/logowanie',
  path: '/logowanie',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelUstawieniaRoute = PanelUstawieniaRouteImport.update({
  id: '/ustawienia',
  path: '/ustawienia',
  getParentRoute: () => PanelRoute,
} as any)
const PanelUslugiRoute = PanelUslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProfilRoute = PanelProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => PanelRoute,
} as any)
const PanelKalendarzRoute = PanelKalendarzRouteImport.update({
  id: '/kalendarz',
  path: '/kalendarz',
  getParentRoute: () => PanelRoute,
} as any)

export interface FileRoutesByFullPath {
  '/logowanie': typeof LogowanieRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/kalendarz': typeof PanelKalendarzRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/uslugi': typeof PanelUslugiRoute
  '/panel/ustawienia': typeof PanelUstawieniaRoute
}
export interface FileRoutesByTo {
  '/logowanie': typeof LogowanieRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/kalendarz': typeof PanelKalendarzRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/uslugi': typeof PanelUslugiRoute
  '/panel/ustawienia': typeof PanelUstawieniaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/logowanie': typeof LogowanieRoute
  '/panel': typeof PanelRouteWithChildren
  '/panel/kalendarz': typeof PanelKalendarzRoute
  '/panel/profil': typeof PanelProfilRoute
  '/panel/uslugi': typeof PanelUslugiRoute
  '/panel/ustawienia': typeof PanelUstawieniaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/logowanie'
    | '/panel'
    | '/panel/kalendarz'
    | '/panel/profil'
    | '/panel/uslugi'
    | '/panel/ustawienia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/logowanie'
    | '/panel'
    | '/panel/kalendarz'
    | '/panel/profil'
    | '/panel/uslugi'
    | '/panel/ustawienia'
  id:
    | '__root__'
    | '/logowanie'
    | '/panel'
    | '/panel/kalendarz'
    | '/panel/profil'
    | '/panel/uslugi'
    | '/panel/ustawienia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LogowanieRoute: typeof LogowanieRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logowanie': {
      id: '/logowanie'
      path: '/logowanie'
      fullPath: '/logowanie'
      preLoaderRoute: typeof LogowanieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel/ustawienia': {
      id: '/panel/ustawienia'
      path: '/ustawienia'
      fullPath: '/panel/ustawienia'
      preLoaderRoute: typeof PanelUstawieniaRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/uslugi': {
      id: '/panel/uslugi'
      path: '/uslugi'
      fullPath: '/panel/uslugi'
      preLoaderRoute: typeof PanelUslugiRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/profil': {
      id: '/panel/profil'
      path: '/profil'
      fullPath: '/panel/profil'
      preLoaderRoute: typeof PanelProfilRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/kalendarz': {
      id: '/panel/kalendarz'
      path: '/kalendarz'
      fullPath: '/panel/kalendarz'
      preLoaderRoute: typeof PanelKalendarzRouteImport
      parentRoute: typeof PanelRoute
    }
  }
}

interface PanelRouteChildren {
  PanelKalendarzRoute: typeof PanelKalendarzRoute
  PanelProfilRoute: typeof PanelProfilRoute
  PanelUslugiRoute: typeof PanelUslugiRoute
  PanelUstawieniaRoute: typeof PanelUstawieniaRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelKalendarzRoute: PanelKalendarzRoute,
  PanelProfilRoute: PanelProfilRoute,
  PanelUslugiRoute: PanelUslugiRoute,
  PanelUstawieniaRoute: PanelUstawieniaRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LogowanieRoute: LogowanieRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
